# Support me by using the funding links below
# Developed and Rasol Unlimited

custom: ['https://app.jibimo.com/direct/RasolUnlimited']

# Your donation means a lot to me to continue the development of open source project like this.
